services:
  api:
    build: ./api
    ports: ["4000:4000"]
    environment:
      JWT_SECRET: "dev-secret-change-me"
      ML_URL: "http://ml:8000"
    volumes:
      - api_data:/app/data
    depends_on:
      - ml

  web:
    build: ./web
    ports: ["5173:5173"]
    environment:
      VITE_API_URL: "http://localhost:4000"
    depends_on:
      - api

  ml:
    build: ./ml
    ports: ["8000:8000"]

volumes:
  api_data:
